<?php
$this->headLink()->appendStylesheet($this->assetUrl('js/Leaflet/0.7.7/leaflet.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('js/Leaflet.draw/0.3.0/leaflet.draw.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet/0.7.7/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet.draw/0.3.0/leaflet.draw.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet.providers/1.1.7/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-form.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.default-view.js', 'Mapping'));

$mapping = null;
$markers = [];
$itemMedia = [];
if (isset($item)) {
    $mapping = $this->api()
        ->searchOne('mappings', ['item_id' => $item->id()])->getContent();
    $markers = $this->api()
        ->search('mapping_markers', ['item_id' => $item->id()])->getContent();
    $itemMedia = $item->media();
}
?>
<fieldset id="mapping-section" class="section">
    <legend id="mapping-legend"><?php echo $this->translate('Mapping'); ?></legend>
    <div id="mapping-map" style="height:500px;"
        data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"
        data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>"
    ></div>
    <div id="mapping-sidebar" class="always-open sidebar">
        <p>Add a Web Map Service (WMS) overlay to the map by providing information below:</p>
        <label>Base URL<br>
        <input type="text" id="mapping-wms-base-url" style="width:100%"></label>
        <label>Layers (comma-separated)<br>
        <input type="text" id="mapping-wms-layers" style="width:100%"></label>
        <label>Styles (comma-separated)<br>
        <input type="text" id="mapping-wms-styles" style="width:100%"></label>
        <label>Label<br>
        <input type="text" id="mapping-wms-label" style="width:100%"></label>
        <button id="mapping-wms-add">Add WMS Overlay</button>
        <button id="mapping-wms-unset">Unset</button>
    </div>
    <div id="mapping-marker-image-selector" class="sidebar">
        <h3>Select Marker Image</h3>
        <label style="font-size:16px;">
            <input type="radio" class="mapping-marker-image-select" name="marker-image" value="" checked> No Image
        </label>
        <?php foreach ($itemMedia as $media): ?>
        <?php if ($media->hasThumbnails()): ?>
        <label style="cursor:pointer;">
            <input type="radio" class="mapping-marker-image-select" name="marker-image" style="display:none;"
                value="<?php echo $this->escapeHtml($media->id()); ?>"
                data-media-thumbnail-url="<?php echo $this->escapeHtml($media->thumbnailUrl('medium')); ?>"
                data-media-title="<?php echo $this->escapeHtml($media->displayTitle()); ?>">
            <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('medium')); ?>"
                title="<?php echo $this->escapeHtml($media->displayTitle()); ?>">
        </label>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <div id="mapping-form">
        <input type="hidden" name="o-module-mapping:mapping[o:id]">
        <input type="hidden" name="o-module-mapping:mapping[o-module-mapping:default_zoom]" value="">
        <input type="hidden" name="o-module-mapping:mapping[o-module-mapping:default_lat]" value="">
        <input type="hidden" name="o-module-mapping:mapping[o-module-mapping:default_lng]" value="">
    </div>
</fieldset>

<div class="mapping-marker-popup-content" style="display:none;">
    <p>Enter a label for this marker:</p>
    <input type="text" class="mapping-marker-popup-label" size="30">
    <div class="mapping-marker-popup-image-content">
        <p>Select an image for this marker from the sidebar:</p>
        <div class="mapping-marker-popup-image"></div>
    </div>
</div>
