<?php
$this->headLink()->appendStylesheet($this->assetUrl('js/Leaflet/0.7.7/leaflet.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('js/Leaflet.draw/0.3.0/leaflet.draw.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet/0.7.7/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet.draw/0.3.0/leaflet.draw.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet.providers/1.1.7/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping.js', 'Mapping'));

$markers = [];
if (isset($item)) {
    $response = $this->api()->search('mapping_markers', ['item_id' => $item->id()]);
    $markers = $response->getContent();
}
?>
<fieldset id="mapping-section" class="section">
    <legend id="mapping-legend"><?php echo $this->translate('Mapping'); ?></legend>
    <div id="mapping-map" style="height:500px;"
        data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>"></div>
    <div id="mapping-sidebar" class="always-open sidebar">
        <button id="mapping-fit-bounds">Fit bounds</button><br>
        <input type="text" id="mapping-wms-base-url"><button id="mapping-wms-base-url-set">Set WMS</button>
        <div id="mapping-marker-image-selector" class="sidebar">
            <h3>Select Marker Image</h3>
            <label style="font-size:16px;">
                <input type="radio" class="mapping-marker-image-select" name="marker-image" value="" checked> No Image
            </label>
            <?php foreach ($item->media() as $media): ?>
            <?php if ($media->hasThumbnails()): ?>
            <label>
                <input type="radio" class="mapping-marker-image-select" name="marker-image"
                    value="<?php echo $this->escapeHtml($media->id()); ?>"
                    data-media-thumbnail-url="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>">
                <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>" width="140" height="140">
            </label>
            <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="mapping-form"></div>
</fieldset>

<div class="template mapping-marker-popup-content">
    <p>Enter a label for this marker:</p>
    <input type="text" class="mapping-marker-popup-label" size="40">
    <div class="mapping-marker-popup-image-content">
        <p>Select an image for this marker from the sidebar:</p>
        <div class="mapping-marker-popup-image"></div>
    </div>
</div>
