<?php
$mapping = $this->api()->searchOne('mappings', ['item_id' => $item->id()])->getContent();
$features = $this->api()->search('mapping_features', ['item_id' => $item->id()])->getContent();

if (!$mapping && !$features) {
    return;
}

$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet/dist/leaflet.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.markercluster/dist/MarkerCluster.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('css/mapping.css', 'Mapping'));

$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet/dist/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet-providers/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/Leaflet.Deflate/dist/L.Deflate.js', 'Mapping'));

$this->headScript()->appendFile($this->assetUrl('js/mapping-show.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
?>

<div id="mapping-section" class="section">
    <div id="mapping-map" style="height:700px;" data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"></div>
</div>

<?php foreach ($features as $feature): ?>
<?php echo $this->partial('common/mapping-popup', ['feature' => $feature]); ?>
<?php endforeach; ?>
