<?php
$this->headLink()->appendStylesheet($this->assetUrl('js/Leaflet/0.7.7/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet/0.7.7/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/Leaflet.providers/1.1.7/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-show.js', 'Mapping'));

$response = $this->api()->search('mapping_markers', ['item_id' => $item->id()]);
$markers = $response->getContent();
?>
<div id="mapping-section" class="section">
    <div id="mapping-map" style="height:500px;" data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>"></div>
</div>

<?php foreach ($markers as $marker): ?>
<div class="template mapping-marker-popup-content" data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>">
    <h4><?php echo $this->escapeHtml($marker->label()); ?></h4>
    <?php if ($marker->media()): ?>
    <img src="<?php echo $this->escapeHtml($marker->media()->thumbnailUrl('medium')); ?>">
    <?php endif; ?>
</div>
<?php endforeach; ?>
