<?php
$label = $feature->label();
$media = $feature->media();
$item = $feature->item();
?>

<?php if ($label): ?>
<h3><?php echo $this->escapeHtml($label); ?></h3>
<?php endif; ?>

<?php if ($media): ?>
<?php echo $this->thumbnail($media, 'medium'); ?>
<div><?php echo sprintf($this->translate('Media: %s'), $media->link($media->displayTitle(null, $this->lang()), null, ['target' => '_blank'])); ?></div>
<?php endif; ?>

<div><?php echo sprintf($this->translate('Item: %s'), $item->link($item->displayTitle(null, $this->lang()), null, ['target' => '_blank'])); ?></div>
