<?php
$property = $this->api()->read('properties', $group['property_id'])->getContent();
$resource = $this->api()->read('resources', $group['resource_id'])->getContent();
$itemSet = $group['item_set_id'] ? $this->api()->read('item_sets', $group['item_set_id'])->getContent() : null;
$resourceClass = $group['resource_class_id'] ? $this->api()->read('resource_classes', $group['resource_class_id'])->getContent() : null;
?>
<span class="group-type"><?php echo $property->label(); ?></span>
<span class="group-value"><?php echo $resource->linkPretty(); ?></span>
<button type="button" class="mapping-show-group-item-features"><?php echo sprintf($this->translate('View all results (%s total)'), $group['count']); ?></button>

<div class="mapping-search-filters-template" style="display: none">
    <div class="filter">
        <div class="filter-label"><?php echo sprintf($this->translate('%s is resource with ID'), $property->label()); ?></div>
        <div class="filter-value"><?php echo $group['resource_id']; ?></div>
    </div>
    <?php if ($itemSet): ?>
    <div class="filter">
        <div class="filter-label"><?php echo $this->translate('In item set'); ?></div>
        <div class="filter-value"><?php echo $itemSet->displayTitle(); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($resourceClass): ?>
    <div class="filter">
        <div class="filter-label"><?php echo $this->translate('Class'); ?></div>
        <div class="filter-value"><?php echo $resourceClass->label(); ?></div>
    </div>
    <?php endif; ?>
</div>
