<?php
$wmsOverlayTemplate = '
<li class="mapping-wms-overlay">
    <input type="checkbox" class="mapping-wms-open">
    <span class="mapping-wms-overlay-title"></span>
    <ul class="actions">
        <a href="#" class="mapping-wms-overlay-edit o-icon-edit" aria-label="Edit" title="Edit" ></a>
        <a href="#" class="mapping-wms-overlay-delete o-icon-delete" aria-label="Delete" title="Delete"></a>
    </ul>
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][label]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][base_url]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][layers]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][styles]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][open]">
</li>';
?>
<a href="#" class="mapping-map-expander expand"><h4>Default Center and Zoom</h4></a>
<div class="collapsible">
    <div class="mapping-map" style="height:300px;">
        <input type="hidden" name="o:block[__blockIndex__][o:data][default_view][zoom]" value="<?php echo $this->escapeHtml($data['default_view']['zoom']); ?>">
        <input type="hidden" name="o:block[__blockIndex__][o:data][default_view][lat]" value="<?php echo $this->escapeHtml($data['default_view']['lat']); ?>">
        <input type="hidden" name="o:block[__blockIndex__][o:data][default_view][lng]" value="<?php echo $this->escapeHtml($data['default_view']['lng']); ?>">
    </div>
</div>

<a href="#" class="expand"><h4>Web Map Service (WMS) Overlays</h4></a>
<div class="collapsible">
    <p>Add, edit, and delete WMS overlays below. You may check which overlay you want open by default.</p>
    <ul class="mapping-wms-overlays" data-wms-overlay-template="<?php echo $this->escapeHtml($wmsOverlayTemplate); ?>">
        <?php foreach ($data['wms'] as $wmsOverlay): ?>
        <li class="mapping-wms-overlay">
            <input type="checkbox" class="mapping-wms-open"<?php echo $wmsOverlay['open'] ? ' checked="checked"' : '' ?>>
            <span class="mapping-wms-overlay-title"><?php echo $wmsOverlay['label']; ?></span>
            <ul class="actions">
                <a href="#" class="mapping-wms-overlay-edit o-icon-edit" aria-label="Edit" title="Edit" ></a>
                <a href="#" class="mapping-wms-overlay-delete o-icon-delete" aria-label="Delete" title="Delete"></a>
            </ul>
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][label]" value="<?php echo $this->escapeHtml($wmsOverlay['label']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][base_url]" value="<?php echo $this->escapeHtml($wmsOverlay['base_url']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][layers]" value="<?php echo $this->escapeHtml($wmsOverlay['layers']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][styles]" value="<?php echo $this->escapeHtml($wmsOverlay['styles']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][open]" value="<?php echo $this->escapeHtml($wmsOverlay['open']); ?>">
        </li>
        <?php endforeach; ?>
    </ul>
    <div class="mapping-wms-fields">
        <div class="field">
            <div class="field-meta">
                <label>Label</label>
                <div class="field-description"></div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-label">
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                <label>Base URL</label>
                <div class="field-description"></div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-base-url">
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                <label>Layers</label><a href="#" class="expand"></a>
                <div class="collapsible">
                    <div class="field-description">The WMS layers, if any (comma-separated).</div>
                </div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-layers">
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                <label>Styles</label><a href="#" class="expand"></a>
                <div class="collapsible">
                    <div class="field-description">The WMS styles, if any (comma-separated).</div>
                </div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-styles">
            </div>
        </div>
    </div>
    <button type="button" class="mapping-wms-add">Add Overlay</button>
    <button type="button" class="mapping-wms-edit" style="display:none;">Save Changes</button>
    <button type="button" class="mapping-wms-clear">Clear Inputs</button>
</div>
