<?php
$wmsOverlayTemplate = '
<li class="mapping-wms-overlay">
    <input type="checkbox" class="mapping-wms-open">
    <span class="mapping-wms-overlay-title"></span>
    <ul class="actions">
        <a href="#" class="mapping-wms-overlay-edit o-icon-edit" aria-label="Edit" title="Edit" ></a>
        <a href="#" class="mapping-wms-overlay-delete o-icon-delete" aria-label="Delete" title="Delete"></a>
    </ul>
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][label]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][base_url]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][layers]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][styles]">
    <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][open]">
</li>';
?>
<a href="#" class="mapping-map-expander expand"><h4><?php echo $this->translate('Default View'); ?></h4></a>
<div class="collapsible">
    <p><?php echo $this->translate('Set the default view using the in-map controls.'); ?></p>
    <div class="mapping-map" style="height:300px;">
        <input type="hidden" name="o:block[__blockIndex__][o:data][bounds]" value="<?php echo $this->escapeHtml($data['bounds']); ?>">
    </div>
</div>

<a href="#" class="expand"><h4><?php echo $this->translate('WMS Overlays'); ?></h4></a>
<div class="collapsible">
    <p><?php echo $this->translate('Add, edit, and delete Web Map Service (WMS) overlays below. You may check which overlay you want open by default.'); ?></p>
    <ul class="mapping-wms-overlays" data-wms-overlay-template="<?php echo $this->escapeHtml($wmsOverlayTemplate); ?>">
        <?php foreach ($data['wms'] as $wmsOverlay): ?>
        <li class="mapping-wms-overlay">
            <input type="checkbox" class="mapping-wms-open"<?php echo $wmsOverlay['open'] ? ' checked="checked"' : '' ?>>
            <span class="mapping-wms-overlay-title"><?php echo $wmsOverlay['label']; ?></span>
            <ul class="actions">
                <a href="#" class="mapping-wms-overlay-edit o-icon-edit" aria-label="Edit" title="Edit" ></a>
                <a href="#" class="mapping-wms-overlay-delete o-icon-delete" aria-label="Delete" title="Delete"></a>
            </ul>
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][label]" value="<?php echo $this->escapeHtml($wmsOverlay['label']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][base_url]" value="<?php echo $this->escapeHtml($wmsOverlay['base_url']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][layers]" value="<?php echo $this->escapeHtml($wmsOverlay['layers']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][styles]" value="<?php echo $this->escapeHtml($wmsOverlay['styles']); ?>">
            <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsIndex__][open]" value="<?php echo $this->escapeHtml($wmsOverlay['open']); ?>">
        </li>
        <?php endforeach; ?>
    </ul>
    <div class="mapping-wms-fields">
        <div class="field">
            <div class="field-meta">
                <label><?php echo $this->translate('Label'); ?></label>
                <div class="field-description"></div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-label">
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                <label><?php echo $this->translate('Base URL'); ?></label>
                <div class="field-description"></div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-base-url">
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                <label><?php echo $this->translate('Layers'); ?></label><a href="#" class="expand"></a>
                <div class="collapsible">
                    <div class="field-description"><?php echo $this->translate('The WMS layers, if any (comma-separated).'); ?></div>
                </div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-layers">
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                <label>Styles</label><a href="#" class="expand"></a>
                <div class="collapsible">
                    <div class="field-description"><?php echo $this->translate('The WMS styles, if any (comma-separated).'); ?></div>
                </div>
            </div>
            <div class="inputs">
                <input type="text" class="mapping-wms-styles">
            </div>
        </div>
    </div>
    <button type="button" class="mapping-wms-add"><?php echo $this->translate('Add Overlay'); ?></button>
    <button type="button" class="mapping-wms-edit" style="display:none;"><?php echo $this->translate('Save Changes'); ?></button>
    <button type="button" class="mapping-wms-clear"><?php echo $this->translate('Clear Inputs'); ?></button>
</div>

<a href="#" class="expand"><h4><?php echo $this->translate('Timeline'); ?></h4></a>
<!--
<div class="collapsible">
-->
    <p><?php echo $this->translate('To enable a timeline for this map, select the timestamp and/or interval properties to use when placing items on the timeline.'); ?></p>
    <div class="field">
        <div class="field-meta">
            <label><?php echo $this->translate('Title headline'); ?></label>
            <div class="field-description"></div>
        </div>
        <div class="inputs">
            <?php
            $titleHeadline = new \Zend\Form\Element\Text("o:block[__blockIndex__][o:data][timeline][title_headline]");
            $titleHeadline->setAttributes([
                'value' => isset($data['timeline']['title_headline']) ? $data['timeline']['title_headline'] : null,
            ]);
            echo $this->formElement($titleHeadline);
            ?>
        </div>
    </div>
    <div class="field">
        <div class="field-meta">
            <label><?php echo $this->translate('Title text'); ?></label>
            <div class="field-description"></div>
        </div>
        <div class="inputs">
            <?php
            $titleText = new \Zend\Form\Element\Textarea("o:block[__blockIndex__][o:data][timeline][title_text]");
            $titleText->setAttributes([
                'class' => 'block-html full wysiwyg',
                'value' => isset($data['timeline']['title_text']) ? $data['timeline']['title_text'] : null,
            ]);
            echo $this->formElement($titleText);
            ?>
        </div>
    </div>
    <div class="field">
        <div class="field-meta">
            <label><?php echo $this->translate('Properties'); ?></label>
            <div class="field-description"></div>
        </div>
        <div class="inputs">
            <?php
            echo $this->numericPropertySelect([
                'name' => 'o:block[__blockIndex__][o:data][timeline][data_type_properties]',
                'attributes' => [
                    'class' => 'chosen-select',
                    'data-placeholder' => 'Select property(s)…', // @translate
                    'multiple' => true,
                    'value' => isset($data['timeline']['data_type_properties']) ? $data['timeline']['data_type_properties'] : null,
                ],
                'options' => [
                    'empty_option' => '',
                    'numeric_data_type' => ['timestamp', 'interval'],
                    'numeric_data_type_disambiguate' => true,
                ],
            ]);
            ?>
        </div>
    </div>
<!--
</div>
-->
