<?php
if ($isTimeline) {
    $this->headLink()->appendStylesheet('https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css');
    $this->headScript()->appendFile('https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js');
    $this->headLink()->appendStylesheet($this->assetUrl('css/timeline.css', 'Mapping'));
}

// Set the classes for the mapping block container div.
$classes = ['mapping-block'];
if ($isTimeline) {
    $classes[] = 'timeline';
    $classes[] = $data['timeline']['timenav_position'];
    if ('full_width_below' === $data['timeline']['timenav_position']) {
        $classes[] = 'timenav-full-width-below';
    }
    if ('full_width_above' === $data['timeline']['timenav_position']) {
        $classes[] = 'timenav-full-width-above';
    }
}
?>
<div class="<?php echo implode(' ', $classes); ?>">

    <?php if ($isTimeline): ?>
    <div class='mapping-timeline' style="height: 500px"
        data-data="<?php echo $this->escapeHtml(json_encode($timelineData)); ?>"
        data-options="<?php echo $this->escapeHtml(json_encode($timelineOptions)); ?>"></div>
    <?php endif; ?>

    <div class="mapping-map" style="height:500px;"
        data-data="<?php echo $this->escapeHtml(json_encode($data)); ?>"
        data-disable-clustering="<?php echo $this->siteSetting('mapping_disable_clustering') ? '1' : '0'; ?>"
        data-basemap-provider="<?php echo $this->escapeHtml($this->siteSetting('mapping_basemap_provider')); ?>"
        data-features-url="<?php echo $this->escapeHtml($this->url('site/mapping', ['controller' => 'index', 'action' => 'get-features'], true)); ?>"
        data-feature-popup-content-url="<?php echo $this->escapeHtml($this->url('site/mapping', ['controller' => 'index', 'action' => 'get-feature-popup-content'], true)); ?>"
        data-items-query="<?php echo $this->escapeHtml(json_encode($itemsQuery)); ?>"
        data-features-query="<?php echo $this->escapeHtml(json_encode($featuresQuery)); ?>">
    </div>

</div>
