<div class="mapping-block">

    <div class="mapping-map" style="height:500px;"
        data-data="<?php echo $this->escapeHtml(json_encode($data)); ?>"
        data-disable-clustering="<?php echo $this->siteSetting('mapping_disable_clustering') ? '1' : '0'; ?>"
        data-basemap-provider="<?php echo $this->escapeHtml($this->siteSetting('mapping_basemap_provider')); ?>"
        data-url="<?php echo $this->escapeHtml($this->url('site/mapping', ['controller' => 'index', 'action' => 'get-item-set-item-feature-popups'], true)); ?>"></div>

    <div class="mapping-feature-popups" style="display: none;">
        <?php foreach ($itemSets as $itemSet): ?>
        <?php echo $this->partial('common/mapping-item-set-popup', ['itemSet' => $itemSet['item_set'], 'geography' => $itemSet['geography']]); ?>
        <?php endforeach; ?>
    </div>

</div>

<div class="mapping-block mapping-block-item-set-items" style="display: none;">

    <div class="mapping-map" style="height:500px;"
        data-data="[]"
        data-disable-clustering="<?php echo $this->siteSetting('mapping_disable_clustering') ? '1' : '0'; ?>"
        data-basemap-provider="<?php echo $this->escapeHtml($this->siteSetting('mapping_basemap_provider')); ?>"></div>

    <div class="mapping-feature-popups" style="display: none;"></div>

</div>
