<h4>Web Map Service (WMS) Overlays</h4>
<ul>
    <li class="mapping-wms-data">
        <span class="mapping-wms-label">Foobar (http://example.com)</span>
        <ul class="actions">
            <a href="#" class="o-icon-edit" aria-label="Edit" title="Edit" ></a>
            <a href="#" class="o-icon-delete" aria-label="Delete" title="Delete"></a>
        </ul>
        <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsDataIndex__][base_url]" value="">
        <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsDataIndex__][layers]" value="">
        <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsDataIndex__][styles]" value="">
        <input type="hidden" name="o:block[__blockIndex__][o:data][wms][__mappingWmsDataIndex__][label]" value="">
    </li>
</ul>
<div class="field">
    <div class="field-meta">
        <label>Label</label>
        <div class="field-description"></div>
    </div>
    <div class="inputs">
        <input type="text">
    </div>
</div>
<div class="field">
    <div class="field-meta">
        <label>Base URL</label>
        <div class="field-description"></div>
    </div>
    <div class="inputs">
        <input type="text">
    </div>
</div>
<div class="field">
    <div class="field-meta">
        <label>Layers</label>
        <div class="field-description">The WMS layers, if any (comma-separated).</div>
    </div>
    <div class="inputs">
        <input type="text">
    </div>
</div>
<div class="field">
    <div class="field-meta">
        <label>Styles</label>
        <div class="field-description">The WMS styles, if any (comma-separated).</div>
    </div>
    <div class="inputs">
        <input type="text">
    </div>
</div>
<button type="button" class="mapping-wms-add">Add WMS Overlay</button>
<button type="button" class="mapping-wms-clear">Clear</button>
<h4>Items Attached to Map</h4>
