<?php
use Mapping\Api\Representation\MappingFeatureRepresentation;

if ($isTimeline) {
    $this->headLink()->appendStylesheet('https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css');
    $this->headScript()->appendFile('https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js');
    $this->headLink()->appendStylesheet($this->assetUrl('css/timeline.css', 'Mapping'));
}

// Set the classes for the mapping block container div.
$mappingBlockClasses = ['mapping-block'];
if ($isTimeline) {
    $mappingBlockClasses[] = 'timeline';
    $timenavPosition = $data['timeline']['timenav_position'];
    $mappingBlockClasses[] = $timenavPosition;
    if ('full_width_below' === $timenavPosition) {
        $mappingBlockClasses[] = 'timenav-full-width-below';
    }
    if ('full_width_above' === $timenavPosition) {
        $mappingBlockClasses[] = 'timenav-full-width-above';
    }
}
?>
<div class="<?php echo implode(' ', $mappingBlockClasses); ?>">
    <?php if ($isTimeline): ?>
    <div class='mapping-timeline' style="height: 500px"
        data-data="<?php echo $this->escapeHtml(json_encode($timelineData)); ?>"
        data-options="<?php echo $this->escapeHtml(json_encode($timelineOptions)); ?>"
    ></div>
    <?php endif; ?>
    <div class="mapping-map" style="height:500px;"
        data-data="<?php echo $this->escapeHtml(json_encode($data)); ?>"
        data-disable-clustering="<?php echo $this->siteSetting('mapping_disable_clustering') ? '1' : '0'; ?>"
        data-basemap-provider="<?php echo $this->escapeHtml($this->siteSetting('mapping_basemap_provider')); ?>"
    ></div>

    <?php foreach ($features as $feature): ?>
    <?php if ($feature instanceof MappingFeatureRepresentation): ?>
        <?php echo $this->partial('common/mapping-feature-popup', ['feature' => $feature]); ?>
    <?php elseif (is_array($feature) && isset($feature['item_set'])): ?>
    <div class="mapping-feature-popup-content" style="display:none;" data-feature-geography="<?php echo $this->escapeHtml($feature['geography']); ?>">
        <h3><?php echo $feature['item_set']->displayTitle(); ?></h3>
        <button type="button" class="mapping-show-item-set-item-features"><?php echo $this->translate('Show all'); ?></button>
    </div>
    <?php endif; ?>
    <?php endforeach; ?>
</div>
