<?php
$translate = $this->plugin('translate');
?>
<div id="mapping-module" class="mapping-group">
    <a href="#" class="expand" aria-label="<?php echo $translate('Expand'); ?>">
        <h4><?php echo $translate('Mapping info'); ?></h4>
    </a>
    <div class="collapsible">
        <h5><?php echo $this->translate('Markers'); ?></h5>
        <select name="mapping-marker" class="flags" data-flag-class="mapping-marker" data-flag-unique="1" data-flag-label="<?php echo $translate('Mapping'); ?>">
            <option><?php echo $translate('Select below'); ?></option>
            <option value="1" data-flag-name="column-map-lat"><?php echo $translate('Latitude'); ?></option>
            <option value="1" data-flag-name="column-map-lng"><?php echo $translate('Longitude'); ?></option>
            <option value="1" data-flag-name="column-map-latlng"><?php echo $translate('Latitude/longitude'); ?></option>
        </select>
        <h5><?php echo $this->translate('Default view settings'); ?></h5>
        <select name="mapping-defaults" class="flags" data-flag-class="mapping-defaults" data-flag-unique="1" data-flag-label="<?php echo $translate('Mapping'); ?>">
            <option><?php echo $translate('Select below'); ?></option>
            <option value="1" data-flag-name="column-default-lat"><?php echo $translate('Default latitude'); ?></option>
            <option value="1" data-flag-name="column-default-lng"><?php echo $translate('Default longitude'); ?></option>
            <option value="1" data-flag-name="column-default-zoom"><?php echo $translate('Default zoom'); ?></option>
        </select>
        <p><?php echo $this->translate('The multivalue separator only applies to Latitude/longitude and allows to import multiple markers.'); ?></p>
    </div>
</div>
