<?php
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) ? $data['label'] : $this->translate($this->getLabel());
?>
<label><?php echo $this->translate('Type'); ?> <input type="text" value="<?php echo $escape($this->translate($this->getLabel())); ?>" disabled></label>
<label><?php echo $this->translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
