<div>
    <span><?php echo $this->translate('Copy action'); ?></span>
    <span style="float: right;"><?php echo $this->formElement($element->getCopyActionElement()) ?></span>
</div>

<div id="mapping-copy-coordinates-by-property">
    <?php echo $this->formElement($element->getPropertyElement()) ?>
    <div>
        <span><?php echo $this->translate('Order'); ?></span>
        <span style="float: right;"><?php echo $this->formElement($element->getOrderElement()) ?></span>
    </div>
    <div>
        <span><?php echo $this->translate('Delimiter'); ?></span>
        <span style="float: right;"><?php echo $this->formElement($element->getDelimiterElement()) ?></span>
    </div>
</div>

<div id="mapping-copy-coordinates-by-properties">
    <?php echo $this->formElement($element->getPropertyLatElement()) ?>
    <?php echo $this->formElement($element->getPropertyLngElement()) ?>
</div>

<div id="mapping-copy-coordinates-on-duplicate">
    <span><?php echo $this->translate('Copy duplicates?'); ?></span>
    <span style="float: right;"><?php echo $this->formElement($element->getCopyDuplicatesElement()) ?></span>
</div>

<script>
const byPropertyDiv = $('#mapping-copy-coordinates-by-property');
const byPropertiesDiv = $('#mapping-copy-coordinates-by-properties');
const onDuplicateDiv = $('#mapping-copy-coordinates-on-duplicate');
byPropertyDiv.hide();
byPropertiesDiv.hide();
onDuplicateDiv.hide();
$('[name="mapping_copy_coordinates[copy_action]"]').on('change', function(e) {
    const thisRadio = $(this);
    switch (thisRadio.val()) {
        case 'by_property':
            byPropertyDiv.show();
            byPropertiesDiv.hide();
            onDuplicateDiv.show();
            break;
        case 'by_properties':
            byPropertyDiv.hide();
            byPropertiesDiv.show();
            onDuplicateDiv.show();
            break;
        default:
            byPropertyDiv.hide();
            byPropertiesDiv.hide();
            onDuplicateDiv.hide();
    }
});
</script>
