<?php echo $this->formElement($element->getLabelPropertyElement()); ?>
<div>
    <span><?php echo $this->translate('Label source'); ?></span>
    <span style="float: right;"><?php echo $this->formElement($element->getLabelPropertySourceElement()) ?></span>
</div>
<div>
    <span><?php echo $this->translate('Media image'); ?></span>
    <span style="float: right;"><?php echo $this->formElement($element->getImageElement()) ?></span>
</div>
